rem azzera DB...
Console START %~f0

Console SAUROTEST MBM41LIB_M DELETE LOC
Console SAUROTEST MBM41LIB_M DELETE MAC
Console SAUROTEST MBM41LIB_M DELETE ATT
Console SAUROTEST MBM41LIB_M DELETE ITM
Console SAUROTEST MBM41LIB_M DELETE BPR
Console SAUROTEST MBM41LIB_M DELETE POH-ODM
Console SAUROTEST MBM41LIB_M DELETE SOH

rem OPR AS400 In mutua esclusione con OPRX3
Console SAUROTEST MBM41LIB_M DELETE OPR
rem OPR X3. In mutua esclusione con OPR
rem Console SAUROTEST MBM41LIB_M DELETE OPRX3

Console SAUROTEST MBM41LIB_M DELETE GIAC
Console SAUROTEST MBM41LIB_M DELETE DISBAS
Console SAUROTEST MBM41LIB_M DELETE DEM
Console SAUROTEST MBM41LIB_M DELETE CIC

rem rigenera db...
Console SAUROTEST MBM41LIB_M ALLTIME LOC
Console SAUROTEST MBM41LIB_M ALLTIME MAC
Console SAUROTEST MBM41LIB_M ALLTIME ATT

rem Console SAUROTEST MBM41LIB_M ALLTIME ITM COD=MSB02005-0%
Console SAUROTEST MBM41LIB_M ALLTIME ITM 

Console SAUROTEST MBM41LIB_M ALLTIME BPR

rem Console SAUROTEST MBM41LIB_M ALLTIME POH-ODM COD=IT001-ODM180062%
rem Console SAUROTEST MBM41LIB_M ALLTIME POH-OFA COD=IT001-OFA180063%
Console SAUROTEST MBM41LIB_M ALLTIME POH-ODM 
Console SAUROTEST MBM41LIB_M ALLTIME SOH

rem OPR da AS400 In mutua esclusione con OPRX3
Console SAUROTEST MBM41LIB_M ALLTIME OPR 

rem OPR da X3. In mutua esclusione con OPR
rem Console SAUROTEST MBM41LIB_M ALLTIME OPRX3

Console SAUROTEST MBM41LIB_M ALLTIME GIAC
Console SAUROTEST MBM41LIB_M ALLTIME DISBAS
Console SAUROTEST MBM41LIB_M ALLTIME DEM
Console SAUROTEST MBM41LIB_M ALLTIME CIC



Console INIT_CYB
Console FINALCHECK
Console STOP %~f0
rem fine