rem azzera DB...
Console START

Console SAURO MBM41LIB_M DELETE LOC
Console SAURO MBM41LIB_M DELETE MAC
Console SAURO MBM41LIB_M DELETE ATT
Console SAURO MBM41LIB_M DELETE ITM
Console SAURO MBM41LIB_M DELETE BPR
Console SAURO MBM41LIB_M DELETE POH-ODM
Console SAURO MBM41LIB_M DELETE SOH

rem OPR AS400 In mutua esclusione con OPRX3
Console SAURO MBM41LIB_M DELETE OPR
rem OPR X3. In mutua esclusione con OPR
rem Console SAURO MBM41LIB_M DELETE OPRX3

Console SAURO MBM41LIB_M DELETE GIAC
Console SAURO MBM41LIB_M DELETE DISBAS
Console SAURO MBM41LIB_M DELETE DEM
Console SAURO MBM41LIB_M DELETE CIC

rem rigenera db...
Console SAURO MBM41LIB_M ALLTIME LOC
Console SAURO MBM41LIB_M ALLTIME MAC
Console SAURO MBM41LIB_M ALLTIME ATT

rem Console SAURO MBM41LIB_M ALLTIME ITM COD=MSB02005-0%
Console SAURO MBM41LIB_M ALLTIME ITM 

Console SAURO MBM41LIB_M ALLTIME BPR

rem Console SAURO MBM41LIB_M ALLTIME POH-ODM COD=IT001-ODM180062%
rem Console SAURO MBM41LIB_M ALLTIME POH-OFA COD=IT001-OFA180063%
Console SAURO MBM41LIB_M ALLTIME POH-ODM 
Console SAURO MBM41LIB_M ALLTIME SOH

rem OPR da AS400 In mutua esclusione con OPRX3
Console SAURO MBM41LIB_M ALLTIME OPR 

rem OPR da X3. In mutua esclusione con OPR
rem Console SAURO MBM41LIB_M ALLTIME OPRX3

Console SAURO MBM41LIB_M ALLTIME GIAC
Console SAURO MBM41LIB_M ALLTIME DISBAS
Console SAURO MBM41LIB_M ALLTIME DEM
Console SAURO MBM41LIB_M ALLTIME CIC



Console INIT_CYB
Console FINALCHECK
Console STOP
rem fine